### ISSUE TITLE
Messages in RabbitMQ instance are not persistent

### ISSUE THREAD

**Issue by kaxap** [zhzhussupovkz/bjj_crawler#1]
Even though RabbitMQ queues are declared as durable and messages are sent with a persistent flag set, data from the queues are going to be disappearing upon RabbitMQ instance reboot/rebuild.
The reason is that "hostname" parameter is not set.

Per docker-compose.yml:

```yml
    bjj-rabbit:
        restart: always
        image: rabbitmq:3-management
        volumes:
          - /opt/rabbitdata/bjj:/var/lib/rabbitmq
        environment:
          - RABBITMQ_DEFAULT_USER=rabbitmq
          - RABBITMQ_DEFAULT_PASS=rabbitmq
          - RABBITMQ_HOST=/
          - RABBITMQ_PORT=5672
          - RABBITMQ_HEARTBEAT=0
        ports:
          - "11900:5672"
          - "11901:15672"
```

From https://hub.docker.com/_/rabbitmq/

```
One of the important things to note about RabbitMQ is 
that it stores data based on what it calls the "Node Name", 
which defaults to the hostname. What this means for
usage in Docker is that we should specify -h/--hostname 
explicitly for each daemon so that we don't 
get a random hostname and can keep track of our data...
```

That means, in the current state your RabbitMQ instance persist precisely nothing. This can be checked either by examining /opt/rabbitdata/bjj/mnesia directory or simply rebuilding your docker-compose.

How to fix it: add a "hostname:" parameter after "ports:", e.g.

```yml
        ports:
          - "11900:5672"
          - "11901:15672"
        hostname: bjj-rabbit
```
